### ISSUE TITLE
Setting KUBEIP_FORCEASSIGNMENT to "false" still reassigns the IP of the existing nodes

### ISSUE THREAD

**Issue by spark2ignite** [doitintl/kubeIP#22]
My cluster has only one node.

$ cat deploy/kubeip-configmap.yaml
```
apiVersion: v1
data:
  KUBEIP_LABELKEY: "kubeip"
  KUBEIP_LABELVALUE: "cluster-1"
  KUBEIP_NODEPOOL: "default-pool"
  KUBEIP_FORCEASSIGNMENT: "false"
kind: ConfigMap
metadata:
  labels:
    app: kubeip
  name: kubeip-config
  namespace: default
```

Log output:
```
$ kubectl logs -f kubeip-8968b4d98-htdw6
time="2018-06-28T08:09:01Z" level=info msg="kubeIP is starting" Build Date="2018-06-26-06:03" Cluster name=cluster-1 Project name=doit-playground Version=bf0d9612f00f7363a58327c21857cd4102f5f6d6
time="2018-06-28T08:09:01Z" level=info msg="Starting forceAssignment" function=forceAssignment pkg=kubeip
time="2018-06-28T08:09:01Z" level=info msg="Collecting Node List..." function=processAllNodes pkg=kubeip
time="2018-06-28T08:09:01Z" level=info msg="Starting kubeip controller" pkg=kubeip-node
time="2018-06-28T08:09:01Z" level=info msg="kubeip controller synced and ready" pkg=kubeip-node
time="2018-06-28T08:09:02Z" level=info msg="Found un assigned node gke-cluster-1-default-pool-e5acb86c-tzrs" function=processAllNodes pkg=kubeip
time="2018-06-28T08:09:02Z" level=info msg="Working on gke-cluster-1-default-pool-e5acb86c-tzrs in zone us-central1-a" function=Kubeip pkg=kubeip
time="2018-06-28T08:09:03Z" level=info msg="Found reserved address 35.188.2.192" function=replaceIP pkg=kubeip
time="2018-06-28T08:09:46Z" level=error msg="ZoneOperations.Get \"Get https://www.googleapis.com/compute/v1/projects/doit-playground/zones/us-central1-a/operations/operation-1530173357207-56faf3f66add8-f0e7d0d6-826d4735?alt=json: read tcp 10.8.0.13:37408->108.177.112.95:443: read: connection reset by peer\" operation-1530173357207-56faf3f66add8-f0e7d0d6-826d4735"
time="2018-06-28T08:09:46Z" level=info msg="Replaced IP for gke-cluster-1-default-pool-e5acb86c-tzrs zone us-central1-a new ip 35.188.2.192" function=replaceIP pkg=kubeip
time="2018-06-28T08:09:53Z" level=error msg="Get https://10.11.240.1:443/api/v1/nodes?labelSelector=kubip_assigned%3D35-188-2-192: read tcp 10.8.0.13:52992->10.11.240.1:443: read: connection reset by peer"
time="2018-06-28T08:09:53Z" level=info msg="Tagging node gke-cluster-1-default-pool-e5acb86c-tzrs as 35.188.2.192" function=tagNode pkg=kubeip
```
